### ISSUE TITLE
Greetings From HackersCardgame.ch

### ISSUE THREAD

**Issue by HackersCardgame** [B4UDW3RK5/Hackers#1]
Hello @B4UDW3RK5 

i created also a "HackersCardgame", it's on https://hackerscardgame.ch or on my github account.

Quoting the Movie has maybe some disadvantages

1. you may run into copyright things
2. not interesting for people that haven't seen the movie "Hackers"
3. being a hacker is about attitudes, so
4. mine are more learning cards than playing cards, autistic people love cards
5. my old HackersCardgame has about 421 cards that are unfortunately the texts somehow broken: https://github.com/HackersCardgame/HackersCardgame23/tree/main/jpg/EN
6. maybe you would like to use some open source format like SVG and cc0 content for your cards
7. in my hackerscardgame there is a script to render an A4 Sheet with 8 A7 cards automatically, this makes sense if you have a lot of cards: https://github.com/HackersCardgame/HackersCardgame_2.0/blob/master/scripts.bookworm/generateSVGs2.sh
8. my new HackersCardgame_2.0 has so far 16 Cards about neurology, brainjacking, implants and so on
9. your design is nicer than mine

![ne13](https://user-images.githubusercontent.com/74041568/194103605-6ca31c2a-0bf9-4bd0-8820-8640df59557e.png) ![ne12](https://user-images.githubusercontent.com/74041568/194103623-624eb344-2fc8-4e5c-b4e5-9bf33d694640.png)
![ne11](https://user-images.githubusercontent.com/74041568/194103636-11cd5b71-4a11-4607-a82a-43d8a1d175eb.png) ![ne10](https://user-images.githubusercontent.com/74041568/194103654-5f59373f-662b-457c-af96-5391faf6f00f.png)
![ne09](https://user-images.githubusercontent.com/74041568/194103665-cfd7e5aa-ada3-45ff-8a62-91af7343fd95.png) ![ne08](https://user-images.githubusercontent.com/74041568/194103673-0e0d655a-f029-4469-8d07-e096531e1991.png)
![ne07](https://user-images.githubusercontent.com/74041568/194103683-96a061b8-f047-483c-933d-9da866b139bb.png) ![ne06](https://user-images.githubusercontent.com/74041568/194103701-d9a117a7-0f85-4c53-80f1-81e15d9fc77f.png)
![ne05](https://user-images.githubusercontent.com/74041568/194103720-46308034-5049-49ce-907b-e2137827efbc.png) ![ne04](https://user-images.githubusercontent.com/74041568/194103729-b7d5b297-76a9-4853-9e82-e1b4a1d8852f.png)
![ne03](https://user-images.githubusercontent.com/74041568/194103733-6dfd2d5f-08d6-454d-870f-bc9e341ed62d.png) ![ne02](https://user-images.githubusercontent.com/74041568/194103742-14f330cc-b532-4b69-96ff-f707c9ebd494.png)
![ne01](https://user-images.githubusercontent.com/74041568/194103752-17bd953f-dbc8-4ae8-9315-88dac1e191af.png) ![in03](https://user-images.githubusercontent.com/74041568/194103765-45f7ea85-a123-4c74-b3fa-d1f77ea70894.png)
![in02](https://user-images.githubusercontent.com/74041568/194103770-f41c0b30-8fee-470f-863f-4681a3255a49.png) ![in01](https://user-images.githubusercontent.com/74041568/194103774-f47279e6-6970-43b0-a4cf-600a0a4e7476.png)

**Comment by B4UDW3RK5** [comment]
hi thanks sorry it took me so long to circle back on this! I appreciate the feedback.

> 1. you may run into copyright things

the worst they can do is tell me to take it down but it's too late, the cat's out of the bag! if I was looking to release a commercial product with the Hackers name attached then I could see where you're coming from.

> 2. not interesting for people that haven't seen the movie "Hackers"

the game is for people who like the movie Hackers, that's why it references the movie so heavily.

> 3. being a hacker is about attitudes, so
> 4. mine are more learning cards than playing cards, autistic people love cards
> 5. my old HackersCardgame has about 421 cards that are unfortunately the texts somehow broken: https://github.com/HackersCardgame/HackersCardgame23/tree/main/jpg/EN

different games for different people I think, yours looks wild but I like a short, quick, small game.

> 6. maybe you would like to use some open source format like SVG and cc0 content for your cards

I could use an open source format but I use what I'm familiar with, regarding the content though, since it's aimed at people who know the film it needs that connection in the artwork.

> 7. in my hackerscardgame there is a script to render an A4 Sheet with 8 A7 cards automatically, this makes sense if you have a lot of cards: https://github.com/HackersCardgame/HackersCardgame_2.0/blob/master/scripts.bookworm/generateSVGs2.sh

thanks! this is helpful but I generally do everything by hand, it's just the way I like to work.

> 8. my new HackersCardgame_2.0 has so far 16 Cards about neurology, brainjacking, implants and so on

I look forward to checking it out!

> 9. your design is nicer than mine

thank you, I appreciate that. I put a lot of love into it.


<3
cat K.
